---
title: "Publications"
---

[Full list of publications on Google Scholar.](https://scholar.google.com/citations?user=QDldimoAAAAJ&hl=en&authuser=1)

# 2021

**Carey MA**, Medlock GL, Alam M, Kabir M,  Uddin MJ, Nayak U, Papin JA, Faruque ASG, Haque R, Petri WA, Jr., Gilchrist CA (2021). **Megasphaera in the stool microbiota is negatively associated with diarrheal cryptosporidiosis.** *Clinical Infectious Diseases.* https://doi.org/10.1093/cid/ciab207. 


# 2020

**Carey MA**, Dräger A, Beber ME, Papin JA , Yurkovich JT (2020). **Community standards to facilitate development and address challenges in metabolic modeling.** *Molecular Systems Biology.* https://doi.org/10.15252/msb.20199235. 

**Carey MA**, Steiner KL, Petri, WA, Jr. (2020). **Ten Simple Rules for reading a scientific paper.** *PLOS Computational Biology.* https://doi.org/10.1371/journal.pcbi.1008032 (corresponding author) *- over 62,000 views since publication on July 30th, 2020*


# 2019

**Carey MA**, Untaroiu AM, Guler JL, Papin JA (2019). **Computational predictions of metabolic drug targets in Chloroquine resistant Plasmodium falciparum for combination therapies.** *BMC Bioinformatics.* https://doi.org/10.1186/s12859-019-2756-y *- co-first authors with undergraduate mentee*
  
Huckaby AC, Granum CS, **Carey MA**, Szlachta L, Al-Barghouthi B, Wang Y, Guler JL (2018. **Complex DNA structures trigger copy number variation across the Plasmodium falciparum genome.** *Nucleic Acids Research.* https://doi.org/10.1093/nar/gky1268

Moutinho MJ, Neubert BC, Jenior ML, **Carey MA**, Medlock GL, Kolling GL, Papin JA (2019). **Functional Anabolic Network Analysis of Human-associated Lactobacillus Strains.** *BioRxiv.* doi: 10.1101/746420.


# 2018

**Carey MA**, Covelli V, Brown A, Medlock GL, Haaren M, Cooper JG, Papin JA, Guler JL (2018). **Influential parameters for the analysis of intracellular parasite metabolomics.** *mSphere* 3(2): e00097-18; https://doi.org/10.1128/mSphere.00097-18

**Carey MA**, Papin JA (2018). **Ten simple rules for biologists learning to program.** *PLOS Computational Biology* 14(1): e1005871. https://doi.org/10.1371/journal.pcbi.1005871 *- PLOS Computational Biology’s most downloaded and shared article (2018), most viewed (2019)*

Medlock GL, **Carey MA**, McDuffie DG, Mundy MB, Giallourou N, Swann JR, Kolling G, Papin JA (2018). **Metabolic mechanisms of interaction within a defined gut microbiota.** *Cell Systems.*
https://doi.org/10.1016/j.cels.2018.08.003 *- Most viewed Cell Systems paper for 3 months.*


# 2017

**Carey MA**, Papin JA, Guler JL (2017) **Novel *Plasmodium falciparum* metabolic network reconstruction identifies shifts associated with clinical antimalarial resistance**. *BMC genomics* 18(1), 543. https://doi.org/10.1186/s12864-017-3905-1

**Carey MA**, Ho ES (2017). **A transcriptome study of *Borrelia burgdorferi* infection in murine heart and brain tissues**. *Journal of Young Investigators* 33(1). https://doi:10.22186/jyi.33.1.28-41


# 2016

Higgins MJ, Serrano A, Boateng KY, Parsons VA, Phuong T, Seifert A, Ricca JM, Tucker KC, Eidelman AS, **Carey MA**, Kurt RA (2016). **A Multifaceted role for Myd88-Dependent signaling in progression of murine mammary carcinoma**. *Breast cancer: basic and clinical research* 10, BCBCR. S40075. 


# 2014
Burgess SL, Buonomo E, **Carey M**, Cowardin C, Naylor C, Noor Z, Wills-Karp M, Petri WA (2014). **Bone marrow dendritic cells from mice with an altered microbiota provide interleukin 17A-dependent protection against *Entamoeba histolytica* colitis**. *MBio* 5(6), e01817. https://doi: 10.1128/mBio.01817-14
	
